#!/usr/bin/env bash
# Cloud Agent install: idempotent dependency + local Postgres bootstrap.
# Runs after checkout. Safe to run repeatedly.
set -euo pipefail

cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "[install] node deps (npm ci)"
npm ci

echo "[install] ensure postgresql is installed"
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq postgresql postgresql-contrib
fi

PG_VER="$(ls /usr/lib/postgresql/ 2>/dev/null | sort -n | tail -1)"
echo "[install] starting postgresql ${PG_VER}/main"
sudo pg_ctlcluster "$PG_VER" main start 2>/dev/null || true

echo "[install] waiting for postgres to accept connections"
for _ in $(seq 1 30); do
  if pg_isready -q -h 127.0.0.1 -p 5432; then break; fi
  sleep 1
done

echo "[install] ensure role + database (idempotent)"
sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='unicred'" | grep -q 1 || \
  sudo -u postgres psql -c "CREATE ROLE unicred LOGIN PASSWORD 'unicred' CREATEDB;"
sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='unicred'" | grep -q 1 || \
  sudo -u postgres createdb -O unicred unicred

if [ ! -f .env.local ]; then
  echo "[install] writing dev .env.local (generated session secret)"
  cat > .env.local <<EOF
# Generated by .cursor/install.sh for local Cloud Agent development.
DATABASE_URL=postgresql://unicred:unicred@127.0.0.1:5432/unicred
BETTER_AUTH_SECRET=$(openssl rand -base64 48)
BETTER_AUTH_URL=http://localhost:3000
NEXT_PUBLIC_SITE_URL=http://localhost:3000
NEXT_PUBLIC_SUPPORT_EMAIL=soporte@unicreditos.com
EOF
else
  echo "[install] .env.local already present, keeping it"
fi

echo "[install] applying schema + seed"
npm run db:push
npm run db:seed

echo "[install] done"
